"""Utility functions and configuration."""

from .config import (
    PROJECT_ROOT,
    DATA_DIR,
    MODELS_DIR,
    WINDOW_SIZE,
    NUM_CHANNELS,
    HORIZONS,
    DEFAULT_HORIZON,
    VAL_RATIO,
    TEST_RATIO,
    CONV_CHANNELS,
    KERNEL_SIZE,
    FC_HIDDEN,
    NUM_CLASSES,
    BATCH_SIZE,
    LEARNING_RATE,
    WEIGHT_DECAY,
    DROPOUT,
    NUM_EPOCHS,
    EARLY_STOPPING_PATIENCE,
    CHECKPOINT_INTERVAL,
    DEVICE,
    get_config_dict,
    print_config,
)
