"""
AutoResearch Reporter — generates RESULTS.md from experiments/results.json.

Called by loop.py after each daemon tick that changes results.
Also callable standalone: python scripts/autoresearch/reporter.py

Output: RESULTS.md in the repo root.
"""

from __future__ import annotations

import json
import re
from datetime import datetime, timezone
from pathlib import Path

REPO_ROOT    = Path(__file__).parent.parent.parent.resolve()
RESULTS_FILE = REPO_ROOT / "experiments" / "results.json"
QUEUE_FILE   = REPO_ROOT / "experiments" / "queue.json"
OUTPUT_FILE  = REPO_ROOT / "RESULTS.md"


# ── Helpers ───────────────────────────────────────────────────────────────────

def _is_leaky(cmd: str) -> bool:
    return bool(re.search(r"--stride\s+1\b", cmd)) and "--shuffle-split" in cmd

def _phase(run_id: str) -> str:
    m = re.search(r"_(p\d+)_", run_id)
    return m.group(1).upper() if m else "P?"

def _fmt_pct(v) -> str:
    if v is None or v == 0:
        return "—"
    return f"{float(v)*100:.1f}%"

def _fmt_time(iso: str) -> str:
    try:
        dt = datetime.fromisoformat(iso.replace("Z", "+00:00"))
        return dt.strftime("%Y-%m-%d")
    except Exception:
        return iso[:10] if iso else "—"

def _verdict_icon(verdict: str, leaky: bool) -> str:
    if leaky:
        return "⚠️ leaky"
    return {"kept": "✅ best", "discarded": "❌", "error": "💥 error",
            "pending": "⏳", "skipped": "⏭️"}.get(verdict, verdict)

def _short_cmd(cmd: str) -> str:
    """Strip --preset sp500 and --samples-per-param 100 (defaults) for brevity."""
    cmd = re.sub(r"--preset\s+sp500\s*", "", cmd)
    cmd = re.sub(r"--samples-per-param\s+100\s*", "", cmd)
    cmd = re.sub(r"\s{2,}", " ", cmd).strip()
    return cmd


# ── Main generator ────────────────────────────────────────────────────────────

def generate() -> str:
    results = json.loads(RESULTS_FILE.read_text()) if RESULTS_FILE.exists() else []
    queue   = json.loads(QUEUE_FILE.read_text())   if QUEUE_FILE.exists()   else []

    cmd_by_id = {e["id"]: e.get("cmd_args", "") for e in queue}

    # Enrich results with cmd / leaky flag
    enriched = []
    for r in results:
        cmd    = cmd_by_id.get(r["run_id"], r.get("config", {}).get("cmd_args", ""))
        leaky  = _is_leaky(cmd)
        test   = r.get("results", {}).get("test_acc", 0.0) or 0.0
        val    = r.get("results", {}).get("best_val_acc", 0.0) or 0.0
        rt     = r.get("results", {}).get("runtime_min")
        mode   = "screen" if "--mode screen" in cmd else "full"
        source = r.get("source", "manual")
        enriched.append({
            "run_id":  r["run_id"],
            "phase":   _phase(r["run_id"]),
            "verdict": r.get("verdict", "?"),
            "leaky":   leaky,
            "test":    test,
            "val":     val,
            "cmd":     cmd,
            "hyp":     r.get("hypothesis", ""),
            "notes":   r.get("notes", ""),
            "date":    _fmt_time(r.get("timestamp", "")),
            "runtime": f"{rt:.0f}m" if rt else "—",
            "mode":    mode,
            "source":  source,
            "kv":      r.get("kaggle_kernel_version"),
        })

    completed = [e for e in enriched if e["verdict"] in ("kept", "discarded", "error")]
    clean     = [e for e in completed if not e["leaky"] and e["test"] > 0]
    leaky     = [e for e in completed if  e["leaky"]]
    pending   = [e for e in queue if e["status"] == "pending"]
    running   = [e for e in queue if e["status"] == "running"]

    best_clean = max(clean, key=lambda e: e["test"], default=None)
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    lines: list[str] = []

    # ── Header ────────────────────────────────────────────────────────────────
    lines += [
        "# CNN Stock Market — Experiment Results",
        "",
        f"> Auto-generated by AutoResearch · Last updated: {now}  ",
        f"> {len(completed)} runs completed · {len(pending)} pending · {len(running)} running",
        "",
    ]

    # ── Best result callout ───────────────────────────────────────────────────
    if best_clean:
        lines += [
            "## 🏆 Current Best",
            "",
            f"| | |",
            f"|---|---|",
            f"| **Run** | `{best_clean['run_id']}` |",
            f"| **Test accuracy** | **{_fmt_pct(best_clean['test'])}** |",
            f"| **Val accuracy** | {_fmt_pct(best_clean['val'])} |",
            f"| **Config** | `{_short_cmd(best_clean['cmd'])}` |",
            f"| **Date** | {best_clean['date']} |",
            f"| **Runtime** | {best_clean['runtime']} |",
            "",
        ]

    # ── Leaderboard ───────────────────────────────────────────────────────────
    lines += [
        "## 📊 Leaderboard (top 20, no data leakage)",
        "",
        "| Rank | Run | Test | Val | Mode | Config | Date |",
        "|------|-----|------|-----|------|--------|------|",
    ]
    for i, e in enumerate(sorted(clean, key=lambda e: e["test"], reverse=True)[:20], 1):
        medal = {1: "🥇", 2: "🥈", 3: "🥉"}.get(i, f"{i}.")
        lines.append(
            f"| {medal} | `{e['run_id']}` | **{_fmt_pct(e['test'])}** | {_fmt_pct(e['val'])} "
            f"| {e['mode']} | `{_short_cmd(e['cmd'])[:60]}` | {e['date']} |"
        )
    lines.append("")

    # ── All experiments by phase ──────────────────────────────────────────────
    lines += ["## 📋 All Experiments", ""]

    phases_order = sorted({e["phase"] for e in enriched},
                          key=lambda p: (len(p), p))
    for phase in phases_order:
        phase_runs = [e for e in enriched if e["phase"] == phase]
        phase_runs.sort(key=lambda e: e["run_id"])
        lines += [f"### {phase}", ""]
        lines += [
            "| Status | Run | Test | Val | Hypothesis | Config | Runtime |",
            "|--------|-----|------|-----|------------|--------|---------|",
        ]
        for e in phase_runs:
            icon = _verdict_icon(e["verdict"], e["leaky"])
            hyp  = (e["hyp"] or e["notes"] or "—")[:70].replace("|", "\\|")
            cmd  = _short_cmd(e["cmd"])[:55].replace("|", "\\|")
            lines.append(
                f"| {icon} | `{e['run_id']}` | {_fmt_pct(e['test'])} | {_fmt_pct(e['val'])} "
                f"| {hyp} | `{cmd}` | {e['runtime']} |"
            )
        lines.append("")

    # ── Pending queue ─────────────────────────────────────────────────────────
    if pending or running:
        lines += ["## ⏳ Queue", ""]
        lines += [
            "| Status | Run | Hypothesis | Config |",
            "|--------|-----|------------|--------|",
        ]
        for e in running:
            hyp = (e.get("hypothesis", "") or "")[:60].replace("|", "\\|")
            cmd = _short_cmd(e.get("cmd_args", ""))[:55].replace("|", "\\|")
            lines.append(f"| 🔄 running | `{e['id']}` | {hyp} | `{cmd}` |")
        for e in pending:
            hyp = (e.get("hypothesis", "") or "")[:60].replace("|", "\\|")
            cmd = _short_cmd(e.get("cmd_args", ""))[:55].replace("|", "\\|")
            src = " *(auto)*" if e.get("source") in ("autostrategy", "autostrategy:promotion") else ""
            lines.append(f"| ⏳ pending{src} | `{e['id']}` | {hyp} | `{cmd}` |")
        lines.append("")

    # ── Notes ─────────────────────────────────────────────────────────────────
    if leaky:
        lines += [
            "## ⚠️ Excluded (data leakage)",
            "",
            "These runs used `--stride 1 --shuffle-split`, which causes overlapping windows",
            "to appear in both train and test sets, inflating accuracy. Not valid results.",
            "",
            "| Run | Test (inflated) | Config |",
            "|-----|-----------------|--------|",
        ]
        for e in sorted(leaky, key=lambda e: e["test"], reverse=True):
            lines.append(
                f"| `{e['run_id']}` | {_fmt_pct(e['test'])} | `{_short_cmd(e['cmd'])[:55]}` |"
            )
        lines.append("")

    return "\n".join(lines)


def write_results_md() -> None:
    md = generate()
    OUTPUT_FILE.write_text(md)
    print(f"  📄 RESULTS.md updated ({len(md.splitlines())} lines)")


if __name__ == "__main__":
    write_results_md()
    print(f"Written to {OUTPUT_FILE}")
